name: Android CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Bump version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionCode: 5 + ${{github.run_number}}
        
#     - name: update version file
#       run: |
#         sed -i '13s/[0-9]/6/g' app/build.gradle

#     - name: Build with Gradle
#       run: ./gradlew assembleDebug
      
#     - name: upload APK
#       id: uploadArtifact
#       uses: actions/upload-artifact@v2.2.4
#       with:
#         name: app
#         path: 'app/build/outputs/apk/debug/*.apk'
       
    - name: Add & Commit
    # You may pin to the exact commit or the version.
    # uses: EndBug/add-and-commit@d77762158d703e60c60cf5baa4de52697d1414a3
      uses: EndBug/add-and-commit@v7.4.0
      with:
        add: .
        author_name: dino
        author_email: husky1124@163.com
        branch: master
        message: update version
        github_token: ${{ github.token }}
        
    - name: get versionName/versionCode and set env
      run: |
        echo "versionName=$(echo $(sed -n '14p' app/build.gradle) | sed 's/[^0-9|.]//g')" >> $GITHUB_ENV
        echo "versionCode=$(echo $(sed -n '13p' app/build.gradle) | sed 's/[^0-9|+]//g')" >> $GITHUB_ENV

    - name: push tag
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "${{ env.versionName }}_${{ env.versionCode }}"
   
    - name: Cleanup Gradle Cache
    # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
    # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
